### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by hossy13** [pcah/python-clean-architecture#76]
hi thanks a lot
can you write or record a tutorial for this? :)))

**Comment by lhaze** [comment]
Hi! Nice to see you here.

A guide or a tutorial is a must-have, but the library's stage is too early for this. Too many patterns are missing or their API isn't stable yet. For example, a typical flow of a web application, written along the Principles, should be composed of a chain of following patterns:

- Request
- MessageBus/Gateway
- Event/Command
- Interactor
- Session
- Repository
- Factory
- Aggregate/Entity/ValueObject
- DTO
- DAO

From this chain, only DAO + DTO + Factory (a naive one) + Entity/ValueObject + Interactor are implemented. And DAO & Interactor have to change their API. And even when the patterns are ready and stabilized, the topic is too large for one issue to organize it. That's why I'm closing this issue a `wontfix`.

If you want the library to have a guide/tutorial, you can try to help in the development.
